[package]
name = "aoc2020"
version = "0.1.0"
edition = "2021"

[dependencies]
# Add useful crates, like regex, itertools, etc.
regex = "1.7"
itertools = "0.10"

[[bin]]
name = "day01"
path = "src/day01.rs"

