#!/usr/bin/env python
import os
from datetime import datetime

import click

from advent_of_code.runners import Language
from advent_of_code.solver import ProblemSolver


@click.command()
@click.option('--year', '-y', default=datetime.now().year, help='Year of the problem')
@click.option('--day', '-d', default=datetime.now().day, help='Day of the problem')
@click.option('--language', '-l', default=Language.PYTHON.value, help='Language used')
@click.option('--session_id', '-s', help='AOC session ID')
@click.option('--live_output', '-o', help='Output live from compiled languages', is_flag=True)
def main(year: int, day: int, language: str, session_id: str | None, live_output: bool) -> None:
    session_id = session_id or os.environ.get('AOC_SESSION')
    assert session_id is not None, 'AOC session ID must be provided'
    solver = ProblemSolver(Language(language), year, day, session_id, live_output)
    solver.solve()


if __name__ == '__main__':
    main()
